baseURL = "/"
languageCode = "en-us"
title = "CLIMYID"
themesDir = "themes"
theme = "hugo-whisper-theme"

publishDir = "public"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Changelog"
    url = "/changelog/"
    weight = 2

[params]
  google_analytics_id="11"
  homepage_button_link = '/changelog'
  homepage_button_text = 'View Changelog'
  homepage_intro = 'CLIMYID is a simple cli tool for your server.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "CLIMYID is a simple cli tool for your server."
    meta_og_title = "CLIMYID"
    meta_og_type = "website"
    meta_og_url = "https://cli.my.id"
    meta_og_image = ""
    meta_og_description = "CLIMYID is a simple cli tool for your server."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ertomedia"
    meta_twitter_creator = "@ertomedia"

  [params.logo]
      mobile = "/images/favicon.svg"
      standard  = "/images/favicon.svg"
